Adding the FIcha APSS form to test
FriendsInGlobalHealth/openmrs-docker-2x pull request #12
Opened 2024-08-21 07:54 UTC by milton-mufume

Adding the FIcha APSS form to test

2024-08-21 08:50 UTC, Guimino requested changes
@milton-mufume  please rename your commit messaga to add the Ticket  ID number  OF-28  

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

2024-08-21 08:54 UTC, Guimino requested changes
also change the file name to ficha-apsspp.json

2024-08-21 08:54 UTC, Guimino commented on data/OpenMRS/configuration/ampathforms/Form_ Ficha Apoio Psicossocial e PP Master Card.json
> +  "referencedForms": [],
I think the correct should be "encounter": "APSS: PREVENÇÃO POSITIVA - SEGUIMENTO",

for more details see  https://github.com/mekomsolutions/openmrs-module-initializer/blob/d03d6bd022f76db6adf2744b54f8469f8031bd47/readme/ampathforms.md

2024-11-05 13:18 UTC, ynurmahomed commented
https://github.com/csaude/openmrs-docker-2x/pull/16.

2024-11-05 13:18 UTC, closed without merging